### ISSUE TITLE
Bug in `optimal_control` and `optimal_disturbance`?

### ISSUE THREAD

**Issue by ChoiJangho** [StanfordASL/hj_reachability#10]
Should [this line](https://github.com/StanfordASL/hj_reachability/blob/068103b09855ff1e8b6fb6a3ca64fd2ee1119b14/hj_reachability/dynamics.py#L34) be `return self.optimal_control_and_disturbance(state, time, grad_value)[0]`? (Remove self in the arguments)

Thanks a lot.

**Comment by schmrlng** [comment]
Ah yes, definitely -- thanks for pointing this out!
